export enum ListTypeConstants {
    REQUIREMENTSTATUS = 'REQUIREMENTSTATUS',
    REQUIREMENTTYPE = 'REQUIREMENTTYPE',
    INTREVIEWTYPE = 'INTREVIEWTYPE',
    CLIENTTYPE = 'CLIENTTYPE',
    PAYRATETYPE = 'PAYRATETYPE',
    REVIEWSTATUS = 'REVIEWSTATUS',
    AVAILABILITY = 'AVAILABILITY',
    WORKAUTHORIZATION = 'WORKAUTHORIZATION',
}
export enum RoleShortConstants {
    SUPERADMIN ='SUPERADMIN',
    ADMIN ='ADMIN',
    TALENTASSOCIATE ='TALENTASSOCIATE',
    REVIEWER ='REVIEWER',
}
export enum ReviewStatusConstants {
    PENDINGREVIEW = 'PENDINGREVIEW',
    SHORTLISTED = 'SHORTLISTED',
    REVIEWERREJECTED = 'REVIEWERREJECTED',
    CLIENTREJECTED = 'CLIENTREJECTED',
    WITHDRAWN = 'WITHDRAWN',
    SUBMITTED = 'SUBMITTED',
    REQUESTED = 'REQUESTED',
    SCHEDULED = 'SCHEDULED',
    SUCCESS = 'SUCCESS',
    MISS = 'MISS'

}
export enum RequirementStatusConstants {
    OPEN = 'OPEN',
    INTERVIEWING = 'INTERVIEWING',
    MISS = 'MISS',
    SUCCESS = 'SUCCESS',
    ONHOLD = 'ONHOLD'
}
export enum RequirementTypeConstants {
    FULLTIME = 'FULLTIME',
    CONTRACTOR = 'CONTRACTOR',
    CTH = 'CTH',
    PARTTIME = 'PARTTIME'
}
export enum ConstantModules {
    DASHBOARD = 'DASHBOARD',
    COMPANY = 'COMPANY',
    USER = 'USER',
    CLIENTS = 'CLIENTS',
    CANDIDATE = 'CANDIDATE',
    REVIEWQUEUE = 'REVIEWQUEUE',
    REQUIREMENT = 'REQUIREMENT',
    INTERVIEWSCHEDULE = 'INTERVIEWSCHEDULE',
    REVIEWREGISTRATION ='REVIEWREGISTRATION'
}
